# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(710, 330, 90, 40))
        self.run_button.setObjectName("run_button")
        self.plot_image = QtWidgets.QLabel(self.centralwidget)
        self.plot_image.setGeometry(QtCore.QRect(340, 30, 451, 291))
        self.plot_image.setText("")
        self.plot_image.setPixmap(QtGui.QPixmap("plot.png"))
        self.plot_image.setScaledContents(True)
        self.plot_image.setObjectName("plot_image")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 18))
        self.label.setObjectName("label")
        self.text_threads = QtWidgets.QTextEdit(self.centralwidget)
        self.text_threads.setGeometry(QtCore.QRect(120, 100, 91, 41))
        self.text_threads.setObjectName("text_threads")
        self.text_passwords = QtWidgets.QTextEdit(self.centralwidget)
        self.text_passwords.setGeometry(QtCore.QRect(20, 100, 91, 41))
        self.text_passwords.setObjectName("text_passwords")
        self.system_info_label = QtWidgets.QLabel(self.centralwidget)
        self.system_info_label.setGeometry(QtCore.QRect(20, 60, 281, 41))
        self.system_info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.system_info_label.setObjectName("system_info_label")
        self.get_stress_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_stress_button.setGeometry(QtCore.QRect(610, 330, 90, 40))
        self.get_stress_button.setObjectName("get_stress_button")
        self.score_text = QtWidgets.QTextEdit(self.centralwidget)
        self.score_text.setGeometry(QtCore.QRect(20, 150, 291, 171))
        self.score_text.setObjectName("score_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run_button.setText(_translate("MainWindow", "Run Analysis"))
        self.label.setText(_translate("MainWindow", "Information:"))
        self.text_threads.setPlaceholderText(_translate("MainWindow", "no_threads"))
        self.text_passwords.setPlaceholderText(_translate("MainWindow", "complexity"))
        self.system_info_label.setText(_translate("MainWindow", "loading..."))
        self.get_stress_button.setText(_translate("MainWindow", "Get Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
